services:

    #Handler
    hecommerce.handler.controller:
        class:      Headoo\EcommerceBundle\Handler\ControllerHandler
        arguments:  [ @doctrine.orm.entity_manager, @translator, @form.factory, @router ]

    #Managers
    hecommerce.service.manager:
        class:      Headoo\EcommerceBundle\Model\ServiceManager
        arguments:  [ @doctrine.orm.entity_manager, %headoo_ecommerce.service.entity% ]
    hecommerce.paymentmethod.manager:
        class:      Headoo\EcommerceBundle\Model\PaymentMethodManager
        arguments:  [ @doctrine.orm.entity_manager, %headoo_ecommerce.paymentmethod.entity% ]
    hecommerce.ordereditem.manager:
        class:      Headoo\EcommerceBundle\Model\OrderedItemManager
        arguments:  [ @doctrine.orm.entity_manager, %headoo_ecommerce.ordereditem.entity% ]
    hecommerce.order.manager:
        class:      Headoo\EcommerceBundle\Model\OrderManager
        arguments:  [ @doctrine.orm.entity_manager, %headoo_ecommerce.order.entity%, @service_container ]
    hecommerce.confirmationemail.manager:
        class:      Headoo\EcommerceBundle\Model\ConfirmationEmailManager
        arguments:  [ @doctrine.orm.entity_manager, %headoo_ecommerce.confirmationemail.entity% ]

    #Form Types
    hecommerce.form.type.customergroup:
        class:      Headoo\EcommerceBundle\Form\CustomerGroupType
        tags:
            - { name: form.type, alias: hecommerce_customergroup_form }
        arguments: [ %headoo_ecommerce.customergroup.entity% ]
    hecommerce.form.type.service:
        class:      Headoo\EcommerceBundle\Form\ServiceType
        tags:
            - { name: form.type, alias: hecommerce_service_form }
        arguments:  [ %headoo_ecommerce.customergroup.entity%, %headoo_ecommerce.service.entity%, %headoo_ecommerce.servicerange.entity%, %headoo_ecommerce.pricecurrency.entity%]
    hecommerce.form.type.servicerange:
        class:      Headoo\EcommerceBundle\Form\ServiceRangeType
        tags:
            - { name: form.type, alias: hecommerce_servicerange_form }
        arguments:  [ %headoo_ecommerce.servicerange.entity% ]
    hecommerce.form.type.pricecurrency:
        class:      Headoo\EcommerceBundle\Form\PriceCurrencyType
        tags:
            - { name: form.type, alias: hecommerce_pricecurrency_form }
        arguments:  [ %headoo_ecommerce.pricecurrency.entity% ]
    hecommerce.form.type.paymentmethod:
        class:      Headoo\EcommerceBundle\Form\PaymentMethodType
        tags:
            - { name: form.type, alias: hecommerce_paymentmethod_form }
        arguments:  [ %headoo_ecommerce.paymentmethod.entity% ]

    #Form Types FOS User Bundle
    hecommerce.form.registration:
        class:      Headoo\EcommerceBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: hecommerce_user_registration }
        arguments:  [ %headoo_ecommerce.customergroup.entity%, %headoo_ecommerce.pricecurrency.entity% ]
    hecommerce.form.profile:
        class:      Headoo\EcommerceBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: hecommerce_user_profile }
        arguments:  [ %headoo_ecommerce.customergroup.entity%, %headoo_ecommerce.pricecurrency.entity% ]

    #Event Listener
    hecommerce.locale_listener:
        class:      Headoo\EcommerceBundle\EventListener\LocaleListener
        arguments:  ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    hecommerce.fos_registration_listener:
        class:      Headoo\EcommerceBundle\EventListener\FosRegistrationListener
        tags:
            - { name: kernel.event_subscriber }

    #Twig
    hecommerce.configuration_expose_extension:
        class:      Headoo\EcommerceBundle\Twig\ConfigurationExposeExtension
        arguments:  [@service_container]
        tags:
            - {name: twig.extension}

         